import { StyleSheet } from 'react-native';
import type { AppTheme } from '../../../theme';

export const createManagementStyles = (theme: AppTheme) => StyleSheet.create({
  panel: { flex: 1, backgroundColor: theme.colors.inputBg },
  listContent: { padding: 16, paddingBottom: 100 },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  title: { fontSize: 17, fontWeight: '700', color: theme.colors.secondary, flex: 1 },
  subtitle: { fontSize: 14, color: theme.colors.textSecondary, marginBottom: 4 },
  meta: { fontSize: 12, color: theme.colors.textSecondary },
  badge: {
    backgroundColor: theme.colors.border,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    fontSize: 11,
    color: theme.colors.textSecondary,
    overflow: 'hidden',
  },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  statusText: { fontSize: 10, fontWeight: '700' },
  emptyText: { textAlign: 'center', marginTop: 50, color: theme.colors.textSecondary, paddingHorizontal: 24 },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.35,
    shadowRadius: 8,
  },
  fabText: { color: '#fff', fontSize: 30, fontWeight: '300' },
});
